---
- name: Set Tower 'admin' password to desired 'tower_password' value
  expect:
    command: tower-manage changepassword admin
    responses: 
      Password.*: "{{ tower_password }}"
  become: true
  no_log: True
...
